/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commander;

import commander.cls.controller.AppController;
import commander.cls.controller.DataController;

/**
 *
 * @author Nam
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        AppController.getInstance().setParent(this);
        this.radioHidden.setSelected(AppController.getInstance().getShowHidden());
        this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        btnNotepad = new javax.swing.JButton();
        btnNewFolder = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnZip = new javax.swing.JButton();
        btnUnZip = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnSettings = new javax.swing.JButton();
        btnAbout1 = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        radioHidden = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        tablePanel1 = new commander.cls.TablePanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnCopy = new javax.swing.JButton();
        btnRename = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tablePanel3 = new commander.cls.TablePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UIT Total Commander");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jToolBar1.setFloatable(false);
        jToolBar1.setFocusTraversalPolicyProvider(true);
        jToolBar1.setMargin(new java.awt.Insets(0, 2, 0, 0));
        jToolBar1.setMaximumSize(new java.awt.Dimension(65584, 35));
        jToolBar1.setMinimumSize(new java.awt.Dimension(63, 35));
        jToolBar1.setPreferredSize(new java.awt.Dimension(63, 35));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        btnNotepad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/notepad-icon.png"))); // NOI18N
        btnNotepad.setToolTipText("New txt fle");
        btnNotepad.setBorderPainted(false);
        btnNotepad.setFocusable(false);
        btnNotepad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotepad.setMaximumSize(new java.awt.Dimension(30, 30));
        btnNotepad.setMinimumSize(new java.awt.Dimension(30, 30));
        btnNotepad.setPreferredSize(new java.awt.Dimension(30, 30));
        btnNotepad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotepad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotepadMouseClicked(evt);
            }
        });
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel4.add(btnNotepad);

        btnNewFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/folder-icon.png"))); // NOI18N
        btnNewFolder.setToolTipText("New folder");
        btnNewFolder.setBorderPainted(false);
        btnNewFolder.setFocusable(false);
        btnNewFolder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewFolder.setMaximumSize(new java.awt.Dimension(30, 30));
        btnNewFolder.setMinimumSize(new java.awt.Dimension(30, 30));
        btnNewFolder.setPreferredSize(new java.awt.Dimension(30, 30));
        btnNewFolder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFolderActionPerformed(evt);
            }
        });
        jPanel4.add(btnNewFolder);

        jPanel10.setMaximumSize(new java.awt.Dimension(25, 20));
        jPanel10.setMinimumSize(new java.awt.Dimension(25, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10);

        btnZip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/compress.png"))); // NOI18N
        btnZip.setToolTipText("Compress");
        btnZip.setBorderPainted(false);
        btnZip.setFocusable(false);
        btnZip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnZip.setMaximumSize(new java.awt.Dimension(30, 30));
        btnZip.setMinimumSize(new java.awt.Dimension(30, 30));
        btnZip.setPreferredSize(new java.awt.Dimension(30, 30));
        btnZip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZipActionPerformed(evt);
            }
        });
        jPanel4.add(btnZip);

        btnUnZip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/uncompress.png"))); // NOI18N
        btnUnZip.setToolTipText("Uncompress");
        btnUnZip.setBorderPainted(false);
        btnUnZip.setFocusable(false);
        btnUnZip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnZip.setMaximumSize(new java.awt.Dimension(30, 30));
        btnUnZip.setMinimumSize(new java.awt.Dimension(30, 30));
        btnUnZip.setPreferredSize(new java.awt.Dimension(30, 30));
        btnUnZip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUnZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnZipActionPerformed(evt);
            }
        });
        jPanel4.add(btnUnZip);

        jPanel11.setMaximumSize(new java.awt.Dimension(25, 20));
        jPanel11.setMinimumSize(new java.awt.Dimension(25, 20));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11);

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Settings-icon.png"))); // NOI18N
        btnSettings.setToolTipText("New folder");
        btnSettings.setBorderPainted(false);
        btnSettings.setFocusable(false);
        btnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSettings.setMaximumSize(new java.awt.Dimension(30, 30));
        btnSettings.setMinimumSize(new java.awt.Dimension(30, 30));
        btnSettings.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        jPanel4.add(btnSettings);

        btnAbout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Help-icon.png"))); // NOI18N
        btnAbout1.setToolTipText("Help");
        btnAbout1.setBorderPainted(false);
        btnAbout1.setFocusable(false);
        btnAbout1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout1.setMaximumSize(new java.awt.Dimension(30, 30));
        btnAbout1.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAbout1.setPreferredSize(new java.awt.Dimension(30, 30));
        btnAbout1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbout1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAbout1);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Actions-help-about-icon.png"))); // NOI18N
        btnAbout.setToolTipText("New folder");
        btnAbout.setBorderPainted(false);
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setMaximumSize(new java.awt.Dimension(30, 30));
        btnAbout.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAbout.setPreferredSize(new java.awt.Dimension(30, 30));
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jPanel4.add(btnAbout);

        jPanel9.setMaximumSize(new java.awt.Dimension(25, 20));
        jPanel9.setMinimumSize(new java.awt.Dimension(25, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        radioHidden.setText("Hidden");
        radioHidden.setFocusPainted(false);
        radioHidden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHiddenActionPerformed(evt);
            }
        });
        jPanel3.add(radioHidden);

        jPanel4.add(jPanel3);

        jToolBar1.add(jPanel4);

        getContentPane().add(jToolBar1);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(tablePanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 1);
        flowLayout2.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout2);

        btnCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/copy-icon.png"))); // NOI18N
        btnCopy.setToolTipText("Copy");
        btnCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCopy.setBorderPainted(false);
        btnCopy.setFocusable(false);
        btnCopy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCopy.setMaximumSize(new java.awt.Dimension(30, 30));
        btnCopy.setMinimumSize(new java.awt.Dimension(30, 30));
        btnCopy.setPreferredSize(new java.awt.Dimension(30, 30));
        btnCopy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCopyMouseClicked(evt);
            }
        });
        jPanel7.add(btnCopy);

        btnRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/rename-icon.png"))); // NOI18N
        btnRename.setToolTipText("Rename");
        btnRename.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRename.setBorderPainted(false);
        btnRename.setFocusable(false);
        btnRename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRename.setMaximumSize(new java.awt.Dimension(30, 30));
        btnRename.setMinimumSize(new java.awt.Dimension(30, 30));
        btnRename.setPreferredSize(new java.awt.Dimension(30, 30));
        btnRename.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRenameMouseClicked(evt);
            }
        });
        jPanel7.add(btnRename);

        jPanel2.add(jPanel7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);
        jPanel1.add(tablePanel3);

        getContentPane().add(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotepadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotepadMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNotepadMouseClicked

    private void btnCopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCopyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopyMouseClicked

    private void btnRenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRenameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRenameMouseClicked

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        // TODO add your handling code here:
        DataController.getInstance().newTextDocument();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnNewFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFolderActionPerformed
        // TODO add your handling code here:
        DataController.getInstance().newFolder();
    }//GEN-LAST:event_btnNewFolderActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZipActionPerformed

    private void btnUnZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUnZipActionPerformed

    private void btnAbout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbout1ActionPerformed

    private void radioHiddenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHiddenActionPerformed
        // TODO add your handling code here:
        AppController.getInstance().setShowHidden(radioHidden.isSelected());
    }//GEN-LAST:event_radioHiddenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAbout1;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnNewFolder;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnRename;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnUnZip;
    private javax.swing.JButton btnZip;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton radioHidden;
    private commander.cls.TablePanel tablePanel1;
    private commander.cls.TablePanel tablePanel3;
    // End of variables declaration//GEN-END:variables
}
