/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commander;

import commander.cls.controller.AppController;
import commander.cls.controller.DataController;

/**
 *
 * @author Nam
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        AppController.getInstance().setParent(this);
        this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        btnNotepad = new javax.swing.JButton();
        btnNewFolder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tablePanel1 = new commander.cls.TablePanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnCopy = new javax.swing.JButton();
        btnRename = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tablePanel3 = new commander.cls.TablePanel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jToolBar1.setFloatable(false);
        jToolBar1.setFocusTraversalPolicyProvider(true);
        jToolBar1.setMargin(new java.awt.Insets(0, 2, 0, 0));
        jToolBar1.setMaximumSize(new java.awt.Dimension(65584, 35));
        jToolBar1.setMinimumSize(new java.awt.Dimension(63, 35));
        jToolBar1.setPreferredSize(new java.awt.Dimension(63, 35));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1);
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 51));
        btnNotepad.setBorderPainted(false);
        btnNotepad.setFocusable(false);
        btnNotepad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotepad.setMaximumSize(new java.awt.Dimension(30, 30));
        btnNotepad.setMinimumSize(new java.awt.Dimension(30, 30));
        btnNotepad.setPreferredSize(new java.awt.Dimension(30, 30));
        btnNotepad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotepad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotepadMouseClicked(evt);
            }
        });
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel4.add(btnNotepad);

        btnNewFolder.setBackground(new java.awt.Color(51, 255, 102));
        btnNewFolder.setBorderPainted(false);
        btnNewFolder.setFocusable(false);
        btnNewFolder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewFolder.setMaximumSize(new java.awt.Dimension(30, 30));
        btnNewFolder.setMinimumSize(new java.awt.Dimension(30, 30));
        btnNewFolder.setPreferredSize(new java.awt.Dimension(30, 30));
        btnNewFolder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewFolderActionPerformed(evt);
            }
        });
        jPanel4.add(btnNewFolder);

        jToolBar1.add(jPanel4);

        getContentPane().add(jToolBar1);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(tablePanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 1);
        flowLayout2.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout2);

        btnCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCopy.setBorderPainted(false);
        btnCopy.setFocusable(false);
        btnCopy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCopy.setMaximumSize(new java.awt.Dimension(30, 30));
        btnCopy.setMinimumSize(new java.awt.Dimension(30, 30));
        btnCopy.setPreferredSize(new java.awt.Dimension(30, 30));
        btnCopy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCopyMouseClicked(evt);
            }
        });
        jPanel7.add(btnCopy);

        btnRename.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRename.setBorderPainted(false);
        btnRename.setFocusable(false);
        btnRename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRename.setMaximumSize(new java.awt.Dimension(30, 30));
        btnRename.setMinimumSize(new java.awt.Dimension(30, 30));
        btnRename.setPreferredSize(new java.awt.Dimension(30, 30));
        btnRename.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRenameMouseClicked(evt);
            }
        });
        jPanel7.add(btnRename);

        jPanel2.add(jPanel7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);
        jPanel1.add(tablePanel3);

        getContentPane().add(jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(65584, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 35));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setBorder(null);
        jButton6.setMaximumSize(new java.awt.Dimension(65584, 35));
        jButton6.setMinimumSize(new java.awt.Dimension(35, 35));
        jPanel3.add(jButton6);

        jButton7.setBorder(null);
        jButton7.setMaximumSize(new java.awt.Dimension(65584, 35));
        jButton7.setMinimumSize(new java.awt.Dimension(35, 35));
        jPanel3.add(jButton7);

        jButton8.setBorder(null);
        jButton8.setMaximumSize(new java.awt.Dimension(65584, 35));
        jButton8.setMinimumSize(new java.awt.Dimension(35, 35));
        jPanel3.add(jButton8);

        jButton9.setBorder(null);
        jButton9.setMaximumSize(new java.awt.Dimension(65584, 35));
        jButton9.setMinimumSize(new java.awt.Dimension(35, 35));
        jPanel3.add(jButton9);

        jButton10.setBorder(null);
        jButton10.setMaximumSize(new java.awt.Dimension(65584, 35));
        jButton10.setMinimumSize(new java.awt.Dimension(35, 35));
        jPanel3.add(jButton10);

        getContentPane().add(jPanel3);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotepadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotepadMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNotepadMouseClicked

    private void btnCopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCopyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopyMouseClicked

    private void btnRenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRenameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRenameMouseClicked

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        // TODO add your handling code here:
        DataController.getInstance().newTextDocument();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnNewFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewFolderActionPerformed
        // TODO add your handling code here:
        DataController.getInstance().newFolder();
    }//GEN-LAST:event_btnNewFolderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnNewFolder;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnRename;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar jToolBar1;
    private commander.cls.TablePanel tablePanel1;
    private commander.cls.TablePanel tablePanel3;
    // End of variables declaration//GEN-END:variables
}
