/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commander.cls.controller;

import commander.cls.Enums;

/**
 *
 * @author Nam
 */
public class SettingsPanel extends javax.swing.JPanel {

    private static SettingsPanel instance;
    public static SettingsPanel getInstance() {
        if (instance == null) {
            instance = new SettingsPanel();
        }
        return instance;
    }
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        settingsDialog.pack();
        settingsDialog.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        dragModePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbDragMode = new javax.swing.JComboBox<>();
        sizeUnitPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbSizeUnit = new javax.swing.JComboBox<>();
        sizeUnitPanel1 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        settingsDialog.setTitle("Settings");
        settingsDialog.setModal(true);
        settingsDialog.setPreferredSize(new java.awt.Dimension(400, 175));
        settingsDialog.setResizable(false);
        settingsDialog.getContentPane().setLayout(new javax.swing.BoxLayout(settingsDialog.getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        settingsDialog.getContentPane().add(jPanel1);

        dragModePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        dragModePanel.setMaximumSize(new java.awt.Dimension(32838, 36));
        dragModePanel.setLayout(new javax.swing.BoxLayout(dragModePanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Drag mode   ");
        jLabel2.setMaximumSize(new java.awt.Dimension(75, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(75, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 16));
        dragModePanel.add(jLabel2);

        cbDragMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Copy", "Cut" }));
        cbDragMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDragModeActionPerformed(evt);
            }
        });
        dragModePanel.add(cbDragMode);

        settingsDialog.getContentPane().add(dragModePanel);

        sizeUnitPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        sizeUnitPanel.setMaximumSize(new java.awt.Dimension(32838, 36));
        sizeUnitPanel.setLayout(new javax.swing.BoxLayout(sizeUnitPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Size unit");
        jLabel3.setMaximumSize(new java.awt.Dimension(75, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(75, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 16));
        sizeUnitPanel.add(jLabel3);

        cbSizeUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Byte", "KiloByte", "MegaByte", "GigaByte" }));
        cbSizeUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSizeUnitActionPerformed(evt);
            }
        });
        sizeUnitPanel.add(cbSizeUnit);

        settingsDialog.getContentPane().add(sizeUnitPanel);

        sizeUnitPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        sizeUnitPanel1.setMaximumSize(new java.awt.Dimension(32838, 36));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0);
        flowLayout1.setAlignOnBaseline(true);
        sizeUnitPanel1.setLayout(flowLayout1);

        btnOK.setText("OK");
        btnOK.setMaximumSize(new java.awt.Dimension(69, 32));
        btnOK.setMinimumSize(new java.awt.Dimension(69, 32));
        btnOK.setPreferredSize(new java.awt.Dimension(69, 32));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        sizeUnitPanel1.add(btnOK);

        btnCancel.setText("Cancel");
        btnCancel.setMaximumSize(new java.awt.Dimension(69, 32));
        btnCancel.setMinimumSize(new java.awt.Dimension(69, 32));
        btnCancel.setPreferredSize(new java.awt.Dimension(69, 32));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        sizeUnitPanel1.add(btnCancel);

        settingsDialog.getContentPane().add(sizeUnitPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbDragModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDragModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDragModeActionPerformed

    private void cbSizeUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSizeUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSizeUnitActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        AppController.getInstance().setDragMode(Enums.DragMode.valueOf(cbDragMode.getSelectedItem().toString()));
        AppController.getInstance().setSizeUnit(Enums.SizeUnit.valueOf(cbSizeUnit.getSelectedItem().toString()));
        setSettingsVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setSettingsVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbDragMode;
    private javax.swing.JComboBox<String> cbSizeUnit;
    private javax.swing.JPanel dragModePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog settingsDialog;
    private javax.swing.JPanel sizeUnitPanel;
    private javax.swing.JPanel sizeUnitPanel1;
    // End of variables declaration//GEN-END:variables

    public void setSettingsVisible(boolean visible) {
        cbDragMode.setSelectedItem(AppController.getInstance().getDragMode().toString());
        cbSizeUnit.setSelectedItem(AppController.getInstance().getSizeUnit().toString());
        settingsDialog.setVisible(visible);
    }
}

